title: Wei Wang's Blog
description: 
  Copyright © WW. All rights reserved.
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://nono721.github.io" # change this to the base hostname & protocol for your site

google_analytics: UA-146148719-1

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Wei Wang"
image: /thumbnail-jumbo.png

github_username: NoNo721

email: ww000721@gmail.com

# MathJax LaTex Support, use $$
markdown: kramdown

twitter_username: WWang37154612

plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-seo-tag
  
target-blank:
    rel: nofollow