title: Wei Wang's Blog
description: 
  Created by WW on 2019.7.3. 

  Copyright © WW. All rights reserved.
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://nono721.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "NoNo721"
image: /thumbnail-jumbo.png

github_username: NoNo721

email: ww000721@gmail.com

twitter_username: WWang37154612

plugins:
  - jekyll-target-blank
  - jekyll-feed

target-blank:
    rel: nofollow